export enum Icons {
  AngleDown = 'angle-down',
  AngleRight = 'angle-right',
  Book = 'book',
  CaretLeft = 'caret-left',
  CaretRight = 'caret-right',
  CheckMark = 'check-mark',
  Close = 'close',
  File = 'file',
  Git = 'git',
  List = 'list',
  MaxRestore = 'max-restore',
  Max = 'max',
  MdSplit = 'md-split',
  MdWysiwyg = 'md-wysiwyg',
  Min = 'min',
  ResizeVertical = 'resize-vertical',
  Search = 'search',
  Setting = 'setting',
  Tabs = 'tabs',
  Text = 'text',
  ThreeDots = 'three-dots',
}

export const ICONS_CODEPOINTS: { [key in Icons]: string } = {
  [Icons.AngleDown]: '61697',
  [Icons.AngleRight]: '61698',
  [Icons.Book]: '61699',
  [Icons.CaretLeft]: '61700',
  [Icons.CaretRight]: '61701',
  [Icons.CheckMark]: '61702',
  [Icons.Close]: '61703',
  [Icons.File]: '61704',
  [Icons.Git]: '61705',
  [Icons.List]: '61706',
  [Icons.MaxRestore]: '61707',
  [Icons.Max]: '61708',
  [Icons.MdSplit]: '61709',
  [Icons.MdWysiwyg]: '61710',
  [Icons.Min]: '61711',
  [Icons.ResizeVertical]: '61712',
  [Icons.Search]: '61713',
  [Icons.Setting]: '61714',
  [Icons.Tabs]: '61715',
  [Icons.Text]: '61716',
  [Icons.ThreeDots]: '61717',
};
