export const enum Icons {
  AddDocument = 'addDocument',
  AddFolder = 'addFolder',
  AngleDown = 'angleDown',
  AngleRight = 'angleRight',
  CaretDown = 'caretDown',
  Check = 'check',
  CodeBranch = 'codeBranch',
  CommentQuestion = 'commentQuestion',
  Cross = 'cross',
  Folder = 'folder',
  FolderMinus = 'folderMinus',
  List = 'list',
  MenuDots = 'menuDots',
  Minuss = 'minuss',
  Search = 'search',
  Settings = 'settings',
  Square = 'square',
}
