export const enum Icons {
  AddNew = 'add-new',
  Close = 'close',
  CloudUpload = 'cloud-upload',
  CollapseAll = 'collapse-all',
  Command = 'command',
  CreateNewFolder = 'create-new-folder',
  CreateNewNote = 'create-new-note',
  Extension = 'extension',
  FolderOpen = 'folder-open',
  Folder = 'folder',
  Help = 'help',
  Maximize = 'maximize',
  Minimize = 'minimize',
  MoreHorizontal = 'more-horizontal',
  NotaAiDefault = 'nota-ai-default',
  NotaAiOn = 'nota-ai-on',
  NotificationsActive = 'notifications-active',
  NotificationsOff = 'notifications-off',
  NotificationsUnread = 'notifications-unread',
  Outline = 'outline',
  RestoreWindow = 'restore-window',
  Setting = 'setting',
  SortByAlpha = 'sort-by-alpha',
  SourceControlDefault = 'source-control-default',
  SourceControlOn = 'source-control-on',
}
