export enum Icons {
  AngleDown = 'angle-down',
  AngleRight = 'angle-right',
  Book = 'book',
  CaretLeft = 'caret-left',
  CaretRight = 'caret-right',
  CheckMark = 'check-mark',
  Close = 'close',
  File = 'file',
  Git = 'git',
  List = 'list',
  Max = 'max',
  MdSplit = 'md-split',
  MdWysiwyg = 'md-wysiwyg',
  Min = 'min',
  MultiLayer = 'multi-layer',
  Search = 'search',
  Setting = 'setting',
  Text = 'text',
  ThreeDotsHorizontal = 'three-dots-horizontal',
  ThreeDotsVertical = 'three-dots-vertical',
}
